%YAML:1.0
#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------

# Flag do undistortion
flagDoUndistortion: 1 # 0: do not undistort an image (KITTI), 1: undistort an image

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 667.59708
Camera.fy: 667.40554
Camera.cx: 545.66678
Camera.cy: 395.18554

Camera.k1: -0.296981
Camera.k2: 0.097228
Camera.k3: 0.000187
Camera.p1: -0.000192
Camera.p2: 0.0

Camera.width: 1032
Camera.height: 772

#--------------------------------------------------------------------------------------------
# User setting Parameters
#--------------------------------------------------------------------------------------------

# Parameters of feature tracker
feature_tracker.thres_error: 70.0      
feature_tracker.thres_bidirection: 1.0
feature_tracker.thres_sampson: 0.2
feature_tracker.window_size: 13
feature_tracker.max_level: 6

# Parameters of map update
map_update.thres_parallax: 1.0

# Parameters of feature extractor
feature_extractor.n_features: 100
feature_extractor.n_bins_u: 32
feature_extractor.n_bins_v: 20
feature_extractor.thres_fastscore: 15.0
feature_extractor.radius: 5.0

# Parameters of motion estimator
motion_estimator.thres_1p_error: 120.0 # pixels
motion_estimator.thres_5p_error: 1.0 # pixels
motion_estimator.thres_poseba_error: 5.0 # pixels

# Parameters of scale estimator
scale_estimator.initial_scale: 0.76 # meters
scale_estimator.thres_turn_psi: 1.2 # degrees
scale_estimator.thres_cnt_turns: 7

scale_estimator.thres_age_past_horizon: 20
scale_estimator.thres_age_use: 2
scale_estimator.thres_age_recon: 2
scale_estimator.thres_parallax_use: 0.5 # degrees
scale_estimator.thres_parallax_recon: 20.0 # degrees

# Parameters of keyframe update
keyframe_update.thres_alive_ratio: 0.8
keyframe_update.thres_mean_parallax: 1.0
