%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------

# Flag do undistortion
flagDoUndistortion: 1 # 0: do not undistort an image (KITTI), 1: undistort an image

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 638.242993
Camera.fy: 638.209362
Camera.cx: 370.313109
Camera.cy: 211.734889

Camera.k1: -0.395333
Camera.k2: 0.160590
Camera.p1: -0.000109
Camera.p2: 0.000378
Camera.k3: 0.0

Camera.width: 752
Camera.height: 480

#--------------------------------------------------------------------------------------------
# User setting Parameters
#--------------------------------------------------------------------------------------------

feature_tracker.thres_error: 25.0       
feature_tracker.thres_bidirection: 1.0 
feature_tracker.window_size: 15
feature_tracker.max_level: 5

feature_extractor.n_features: 200
feature_extractor.n_bins_u: 32
feature_extractor.n_bins_v: 20
feature_extractor.thres_fastscore: 20.0
feature_extractor.radius: 10.0

keyframe_update.thres_alive_ratio: 0.7
keyframe_update.thres_mean_parallax: 3.0

map_update.thres_parallax: 1.0
